const GET_ISSUES_LOADING = 'GET_ISSUES_LOADING';
const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
const GET_ISSUES_ERROR = 'GET_ISSUES_ERROR';

const GET_LABELS_LOADING = 'GET_LABELS_LOADING';
const GET_LABELS_SUCCESS = 'GET_LABELS_SUCCESS';
const GET_LABELS_ERROR = 'GET_LABELS_ERROR';

const types = {
    GET_ISSUES_LOADING,
    GET_ISSUES_SUCCESS,
    GET_ISSUES_ERROR,
    GET_LABELS_LOADING,
    GET_LABELS_SUCCESS,
    GET_LABELS_ERROR
};

export default types;