export const GET_GITHUBAUTHKEY_REQUEST = 'GET_GITHUBAUTHKEY_REQUEST';
export const GET_GITHUBAUTHKEY_SUCCESS = 'GET_GITHUBAUTHKEY_SUCCESS';
export const GET_GITHUBAUTHKEY_FAIL = 'GET_GITHUBAUTHKEY_FAIL';
export const EMPTY_GITHUBAUTHKEY_LIST = 'EMPTY_GITHUBAUTHKEY_LIST';
