export const GET_ISSUES_REQUEST = 'GET_ISSUES_REQUEST';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAIL = 'GET_ISSUES_FAIL';
export const EMPTY_ISSUES_LIST = 'EMPTY_ISSUES_LIST';
export const SET_LANGUAGE = 'SET_LANGUAGE';
