export const GET_LABELS_REQUEST = 'GET_LABELS_REQUEST';
export const GET_LABELS_SUCCESS = 'GET_LABELS_SUCCESS';
export const GET_LABELS_FAIL = 'GET_LABELS_FAIL';
export const TOGGLE_MENU = 'TOGGLE_MENU';
