export const ADD_TO_SELECTED_LABELS = 'ADD_TO_SELECTED_LABELS';
export const REMOVE_FROM_SELECTED_LABELS = 'REMOVE_FROM_SELECTED_LABELS';
export const EMPTY_SELECTED_LABELS = 'EMPTY_SELECTED_LABELS';
